// Auto-generated pubsub bridge plugin: @(msg_type)
// Generated by: ros2 agnocast generate-bridge-plugins

#include "generic_functions.hpp"

#include "agnocast/agnocast.hpp"

#include "rclcpp/rclcpp.hpp"
#include "rclcpp/serialization.hpp"
#include "rclcpp/serialized_message.hpp"

#include <memory>
#include <utility>

#include "@(header_path)"

extern "C" PerformancePubsubBridgeResult create_r2a_pubsub_bridge_@(snake_type_name)(
  rclcpp::Node::SharedPtr node,
  const std::string & topic_name,
  const rclcpp::QoS & sub_qos)
{
  using MsgT = @(cpp_type);
  using AgnoPub = agnocast::BasicPublisher<MsgT, agnocast::NoBridgeRequestPolicy>;

  auto agno_pub = std::make_shared<AgnoPub>(
    node.get(),
    topic_name,
    rclcpp::QoS(agnocast::DEFAULT_QOS_DEPTH).transient_local(),
    agnocast::PublisherOptions{},
    true);

  return create_r2a_generic_bridge(
    node, topic_name, sub_qos, "@(msg_type)",
    [agno_pub](std::shared_ptr<rclcpp::SerializedMessage> serialized_msg) {
      static const rclcpp::Serialization<MsgT> serialization;
      auto loaned_msg = agno_pub->borrow_loaned_message();
      try {
        serialization.deserialize_message(serialized_msg.get(), &(*loaned_msg));
      } catch (const std::exception & e) {
        RCLCPP_ERROR(
          rclcpp::get_logger("ros2agnocast"),
          "Failed to deserialize message in r2a bridge: %s",
          e.what());
        return;
      }
      agno_pub->publish(std::move(loaned_msg));
    });
}

extern "C" PerformancePubsubBridgeResult create_a2r_pubsub_bridge_@(snake_type_name)(
  rclcpp::Node::SharedPtr node,
  const std::string & topic_name,
  const rclcpp::QoS & sub_qos)
{
  using MsgT = @(cpp_type);

  auto ros_pub = node->create_generic_publisher(
    topic_name, "@(msg_type)",
    rclcpp::QoS(agnocast::DEFAULT_QOS_DEPTH).reliable().transient_local());

  auto cb_group = node->create_callback_group(rclcpp::CallbackGroupType::MutuallyExclusive);

  auto agno_callback = [ros_pub](const agnocast::ipc_shared_ptr<MsgT> msg) {
    static const rclcpp::Serialization<MsgT> serialization;
    rclcpp::SerializedMessage serialized_msg;
    try {
      serialization.serialize_message(msg.get(), &serialized_msg);
    } catch (const std::exception & e) {
      RCLCPP_ERROR(
        rclcpp::get_logger("ros2agnocast"),
        "Failed to serialize message in a2r bridge: %s",
        e.what());
      return;
    }
    ros_pub->publish(serialized_msg);
  };

  agnocast::SubscriptionOptions sub_opts;
  sub_opts.ignore_local_publications = true;
  sub_opts.callback_group = cb_group;

  using AgnoSub = agnocast::BasicSubscription<MsgT, agnocast::NoBridgeRequestPolicy>;
  auto agno_sub = std::make_shared<AgnoSub>(
    node.get(),
    topic_name,
    sub_qos,
    agno_callback,
    sub_opts,
    true);

  return {agno_sub, cb_group};
}
